#!/bin/bash -e

mkdir -p "$HOME"/.local/share

mkdir build
cd build
export TZ="America/Los_Angeles"
#
#if [[ "$BUILDTYPE" == "cmake-make" ]]; then
#    cmake ../gnucash $PLATFORM_CMAKE_OPTS
#    make -j 4
#    make check || ../afterfailure
#elif [[ "$BUILDTYPE" == "cmake-ninja" ]]; then
    cmake ../gnucash -DWITH_PYTHON=ON -DCMAKE_BUILD_TYPE=debug -G Ninja $PLATFORM_CMAKE_OPTS
    ninja
    
    #ninja check || ../afterfailure;

    ln -s /build/lib/python3/dist-packages/gnucash /usr/lib/python3/dist-packages/gnucash

    cd /build
    python3 -c 'import gnucash'

#else
#    echo "Unknown buildtype: \"$BUILDTYPE\". Not building."
#fi

